/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cc03cb70b7cd334003107f9
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import CardActions from "../redux/actions/CardActions";
import DeckActions from "../redux/actions/DeckActions";

// END IMPORT ACTIONS

/** APIs

* actionsCard.create
*	@description CRUD ACTION create
*
* actionsDeck.findBycards
*	@description CRUD ACTION findBycards
*	@param Objectid key - Id della risorsa cards da cercare
*
* actionsCard.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id 
*
* actionsDeck.list
*	@description CRUD ACTION list
*
* actionsCard.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class CardEdit extends Component {
  // Init card
  constructor(props) {
    super(props);
    this.state = {
      card: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsCard.loadCard(this.props.match.params.id);
      this.props.actionsDeck.findBycards(this.props.match.params.id);
    }
    
    this.props.actionsDeck.loadDeckList();
  }

  // Insert props card in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      card: props.card
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.card._id) {
      this.props.actionsCard.saveCard(this.state.card).then(data => {
        this.props.history.push("/cards/");
      });
    } else {
      this.props.actionsCard.createCard(this.state.card).then(data => {
        this.props.history.push("/cards/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Card Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="description"
            label="Description"
            value={this.state.card.description || ""}
            onChange={Utils.handleChange.bind(this, "card")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.card.name || ""}
            onChange={Utils.handleChange.bind(this, "card")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.card.name && this.state.card.name === ""
              ? { error: true }
              : {})}
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m deck with Deck */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="deck">Deck</InputLabel>
            <Select
              multiple
              value={this.state.card.deck || []}
              onChange={Utils.handleChangeSelect.bind(this, "card")}
              input={<Input id="deck" name="deck" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listDeck && this.props.listDeck.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.card.deck &&
                      this.state.card.deck.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Deck */}
          
          <h3>Deck</h3>
          {(!this.props.listDeck || this.props.listDeck.length === 0) && 
            <div>No Deck associated</div>
          }
          {this.props.listDeck &&
            this.props.listDeck.map((item, i) => {
              return (
                <Link to={"/decks/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/cards/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsCard: bindActionCreators(CardActions, dispatch),
    actionsDeck: bindActionCreators(DeckActions, dispatch),
  };
};

// Validate types
CardEdit.propTypes = { 
  actionsCard: PropTypes.object.isRequired,
  actionsDeck: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    card: state.CardEditReducer.card,
    listDeck: state.CardEditReducer.listDeck,
    listDeck: state.CardEditReducer.listDeck
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CardEdit);
