/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cc03cb70b7cd334003107f9
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import DeckActions from "../redux/actions/DeckActions";

// END IMPORT ACTIONS

/** APIs

* actionsDeck.create
*	@description CRUD ACTION create
*
* actionsDeck.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id 
*
* actionsDeck.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class DeckEdit extends Component {
  // Init deck
  constructor(props) {
    super(props);
    this.state = {
      deck: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsDeck.loadDeck(this.props.match.params.id);
      this.props.actionsCard.findBydeck(this.props.match.params.id);
    }
    
    this.props.actionsCard.loadCardList();
  }

  // Insert props deck in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      deck: props.deck
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.deck._id) {
      this.props.actionsDeck.saveDeck(this.state.deck).then(data => {
        this.props.history.push("/decks/");
      });
    } else {
      this.props.actionsDeck.createDeck(this.state.deck).then(data => {
        this.props.history.push("/decks/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Deck Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="description"
            label="Description"
            value={this.state.deck.description || ""}
            onChange={Utils.handleChange.bind(this, "deck")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.deck.name || ""}
            onChange={Utils.handleChange.bind(this, "deck")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.deck.name && this.state.deck.name === ""
              ? { error: true }
              : {})}
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m cards with Card */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="cards">Cards</InputLabel>
            <Select
              multiple
              value={this.state.deck.cards || []}
              onChange={Utils.handleChangeSelect.bind(this, "deck")}
              input={<Input id="cards" name="cards" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listCard && this.props.listCard.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.deck.cards &&
                      this.state.deck.cards.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Card */}
          
          <h3>Card</h3>
          {(!this.props.listCard || this.props.listCard.length === 0) && 
            <div>No Card associated</div>
          }
          {this.props.listCard &&
            this.props.listCard.map((item, i) => {
              return (
                <Link to={"/cards/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/decks/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsDeck: bindActionCreators(DeckActions, dispatch),
  };
};

// Validate types
DeckEdit.propTypes = { 
  actionsDeck: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    deck: state.DeckEditReducer.deck,
    listCard: state.DeckEditReducer.listCard,
    listCard: state.DeckEditReducer.listCard
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DeckEdit);
